GET http://localhost:8000/passwords

###

GET http://localhost:8000/passwords/611ede95181ac013fee35516

###

POST http://localhost:8000/passwords
Content-Type: application/json

{
  "title": "Facebook",
  "password": "12346578"
}

###

DELETE http://localhost:8000/passwords/611ed2d9824fe18aa0c1a612

###

PUT http://localhost:8000/passwords/611e12440cfd4a820bd83d8b
Content-Type: application/json

{
  "title": "Twitter",
  "password": "adwfawd"
}

###

PUT http://localhost:8000/passwords/611ed2d9824fe18aa0c1a612
Content-Type: application/json

{
  "title": "SHOULD CHANGE"
}
