GET http://localhost:8000/tags

###

POST http://localhost:8000/tags
Content-Type: application/json

{
  "tag": "massar egbari"
}

###

DELETE http://localhost:8000/tags/d61219870b6e9c40fcdf36bd

###

PUT http://localhost:8000/tags/61219870b6e9c40fcdf36bc3
Content-Type: application/json

{
  "tag": "noooo, did it change?!"
}
