# To login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "omarelwy@hotmail.com",
  "password": "12345678"
}

###


GET http://localhost:8000/passwords
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkand0IiwiaWF0IjoxNjI5NzE0MTcyNDcxLCJpZCI6IjYxMjMzOWFmMjc4ODRlNmE4OGE5MGM0NyIsImV4cCI6MTYzMjMwNjE3Mn0.zq75OLQ4lyfuoJODdu3BbzeehjoAs_00mU6tQSbANGzwa7psMMZoDGcMW8G7s_tPKRSibSsNuocSxvRongfjzQ

###

GET http://localhost:8000/passwords/611f531f8685626147cfd37e

###

POST http://localhost:8000/passwords
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkand0IiwiaWF0IjoxNjI5NzEzOTAxNzg0LCJpZCI6IjYxMjMzOWFmMjc4ODRlNmE4OGE5MGM0NyIsImV4cCI6MTYzMjMwNTkwMn0.11lhNUd4exVVHu3HN-SSgttjfYAyVXbQfh2wG1oB2-V79EHaRGaP5h0UY6sR9IUjfyk0JPLQC6mzSTxMjmgxQg

{
  "title": "some other pass",
  "password": "falseaaa"
}

###

DELETE http://localhost:8000/passwords/611ed2d9824fe18aa0c1a612

###

PUT http://localhost:8000/passwords/611e12440cfd4a820bd83d8b
Content-Type: application/json

{
  "title": "Twitter",
  "password": "adwfawd"
}

###

PUT http://localhost:8000/passwords/611ed2d9824fe18aa0c1a612
Content-Type: application/json

{
  "title": "SHOULD CHANGE"
}
