# To login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "omarelwy1@hotmail.com",
  "password": "12345678"
}

###

GET http://localhost:8000/tags
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkand0IiwiaWF0IjoxNjI5NzQ1MzQwNzYyLCJpZCI6IjYxMjMzOWFmMjc4ODRlNmE4OGE5MGM0NyIsImV4cCI6MTYzMjMzNzM0MX0.Ob8xTwowevTcLKXFCEO_mqiJ5TRYrVi7hAYasAV3DPVzG6GNyVZwJ2kN-VvXPTj5ToLJVjB1nFlZsmDNOyTaQw

###

POST http://localhost:8000/tags
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkand0IiwiaWF0IjoxNjI5NzQ2MjMzNzczLCJpZCI6IjYxMjMzOWU5Mjc4ODRlNmE4OGE5MGM0YSIsImV4cCI6MTYzMjMzODIzNH0.s8A6xvLb0gOgY2zeNL6Q9hba5leIFS0Fr5k4BODfA71M_SUJf6D71wZIQV68sHasCfqhW0qiMUjA0bDU8nI3rQ
Content-Type: application/json

{
  "tag": "Lorde"
}

###

DELETE http://localhost:8000/tags/d61219870b6e9c40fcdf36bd

###

PUT http://localhost:8000/tags/61219870b6e9c40fcdf36bc3
Content-Type: application/json

{
  "tag": "noooo, did it change?!"
}
